"use client";
import { useState } from "react";
import { ADMIN_WALLET } from "@/lib/config";
import { useLiveStore } from "@/store/transfer-store";

export function WalletConnect({ title = "Connect your wallet", description = "Connect a wallet to continue.", walletType = "user" }: { title?: string; description?: string; walletType?: "admin" | "user" }) {
  const [connecting, setConnecting] = useState(false); const [error, setError] = useState(""); const connect = useLiveStore(s => s.connectWallet); const isAdmin = walletType === "admin";
  const connectTronLink = async () => { setConnecting(true); setError(""); try { if (!window.tronLink?.request || !window.tronWeb) throw new Error("TronLink was not detected. Install or unlock TronLink, then try again."); await window.tronLink.request({ method: "tron_requestAccounts" }); const address = window.tronWeb.defaultAddress?.base58; if (!address) throw new Error("TronLink did not provide an active wallet address."); const message = `TransferApp sign-in confirmation\nWallet: ${address}\nTimestamp: ${Date.now()}`; const sign = window.tronWeb.trx?.signMessageV2; if (!sign) throw new Error("This TronLink version does not support message signing."); const signature = await sign(message); connect(address, signature); } catch (cause) { setError(cause instanceof Error ? cause.message : "Wallet connection was not confirmed."); } finally { setConnecting(false); } };
  return <div className="mx-auto max-w-xl glass rounded-3xl p-7 md:p-10"><div className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-2xl bg-cyan/10 text-3xl text-cyan">◈</div><div className="text-center"><div className="eyebrow mb-3">TronLink session required</div><h1 className="text-2xl font-semibold text-white">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-400">{description} TronLink will ask you to approve the account connection and sign a login message. No transfer transaction is sent.</p></div><button onClick={connectTronLink} disabled={connecting} className="mt-7 flex w-full items-center justify-center gap-2 rounded-xl bg-cyan py-3 font-bold text-ink transition hover:bg-cyan/90 disabled:cursor-wait disabled:opacity-60">{connecting && <span className="h-4 w-4 animate-spin rounded-full border-2 border-ink/30 border-t-ink" />}{connecting ? "Waiting for TronLink…" : "Connect with TronLink"}</button>{error && <div className="mt-4 rounded-xl border border-red-400/25 bg-red-400/10 p-3 text-sm leading-5 text-red-200">{error}</div>}<div className="mt-4 rounded-xl border border-white/5 bg-white/[.03] p-3 text-xs leading-5 text-slate-500">{isAdmin ? <>Admin access requires the configured TronLink address <span className="mono text-slate-300">{ADMIN_WALLET.slice(0, 8)}…{ADMIN_WALLET.slice(-6)}</span>.</> : "The connected TronLink account becomes the sender wallet for this transfer."}</div></div>;
}
